# Maximum distance for clicks on a map
max-click-range: 25

# Time in seconds before an unused image is removed from RAM
image-idle-unload-time: 1800

# Display animations
animations: true

# Timespan of the load statistics rolling average in seconds
statistics-average-time: 100