name: Luma
main: zedly.luma.Luma
version: 1.2.0
api-version: 1.14
author: Zedly

commands:
  lu:
    description: "Use the Luma plugin"
    aliases: [luma]
    usage: "/lu [create/update/set-speed/action/info]"
    permission: luma.luma

permissions:
  luma.*:
    description: Gives access to all subordinate nodes for convenience.
    children:
      luma.list: true
      luma.luma: true
      luma.create: true
      luma.info: true
      luma.update: true
      luma.print: true
      luma.action: true
      luma.setspeed: true
      luma.stats: true

  luma.info:
    description: Display information about a Luma picture
    default: false
    
  luma.list:
    description: List existing Luma images
    default: false
    
  luma.luma:
    description: Access /lu
    default: false
    
  luma.create:
    description: Create new Luma images
    default: false
    
  luma.update:
    description: Change the content of an image
    default: false
  
  luma.print:
    description: Spawn map items containing an image
    default: false
  
  luma.setspeed:
    description: Change the speed of an animation
    default: false
  
  luma.action:
    description: Change the special function of a Luma map
    default: false
    
  luma.stats:
    description: See Luma's CPU and RAM usage
    default: false
