name: Luma
main: zedly.luma.Luma
version: 1.1.0
author: Zedly

commands:
  lu:
    description: Open your Tricorder, switch to a menu.
    aliases: [luma]
    usage: /lu [create/changeto/speed/action]
    permission: luma.luma

permissions:
  luma.luma:
    description: Gives access to all subordinate nodes for convenience.
    